project '../iOS/HarmonyTi.xcodeproj'

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.0'

require 'json'
podfile_properties_path = File.join(__dir__, '..', 'podfile.properties.json')
podfile_properties = File.exist?(podfile_properties_path) ? JSON.parse(File.read(podfile_properties_path)) : {}

target 'HarmonyTi' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  target 'HarmonyTiTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end
